using System.Linq;
using Microsoft.CodeAnalysis;

namespace AutoPatterns.Utils
{
    internal class GeneratorUtils
    {
        public static AttributeData? GetAttribute(ISymbol typeSymbol, ISymbol attributeSymbol) =>
            typeSymbol.GetAttributes().FirstOrDefault(ad =>
                ad?.AttributeClass is { } @class && @class.Equals(attributeSymbol, SymbolEqualityComparer.Default));

        public const string HEADER = @"/* <auto-generated>
     This code was generated by a tool. Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 </auto-generated> */";
    }
}
